name: shared
description: "Shared module for Money Tracker application."
version: 0.0.1
publish_to: "none"
resolution: "workspace"

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  get_it: ^9.0.5
  hive_ce_flutter: ^2.3.3
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen: ^5.12.0
  flutter_gen_runner: ^5.12.0
  build_runner: ^2.10.1

flutter:
  fonts:
    - family: ibmPlexSansThai
      fonts:
        - asset: ../../assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Thin.ttf
          weight: 100
        - asset: ../../assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-ExtraLight.ttf
          weight: 200
        - asset: ../../assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Light.ttf
          weight: 300
        - asset: ../../assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Regular.ttf
          weight: 400
        - asset: ../../assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Medium.ttf
          weight: 500
        - asset: ../../assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-SemiBold.ttf
          weight: 600
        - asset: ../../assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Bold.ttf
          weight: 700

flutter_gen:
  output: ./lib/gen
  line_length: 120
  assets:
    enabled: true
    outputs:
      style: dot-delimiter
      class_name: Assets
