name: shared
description: "Shared module for Money Tracker application."
version: 0.0.1
publish_to: "none"
resolution: "workspace"

executables:
  create_feature:
  create_locale_keys:

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.9.0
  easy_localization: ^3.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  fpdart: ^1.2.0
  freezed_annotation: ^3.1.0
  get_it: ^9.0.5
  go_router: ^17.0.0
  google_sign_in: ^7.2.0
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  json_annotation: ^4.9.0
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  synchronized: ^3.4.0
  ua_client_hints: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  hive_ce_generator: ^1.10.0
  intl_utils: ^2.8.12
  flutter_gen: ^5.12.0
  flutter_gen_runner: ^5.12.0

flutter:
  assets:
    - ./assets/translations/

flutter_gen:
  output: ./lib/generated
  line_length: 120
  assets:
    enabled: true
    outputs:
      style: dot-delimiter
      class_name: UiAssets
      package_parameter_enabled: true
    exclude:
      - assets/translations/**
