name: ui
description: "UI module for Money Tracker application."
version: 0.0.1
publish_to: "none"
resolution: "workspace"

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  go_router: ^17.0.0
  shared:
    path: ../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_intl:
  enabled: true
  main_locale: th
  class_name: UILocalizations
  arb_dir: lib/gen/l10n
  output_dir: lib/gen
