name: widgetbook_workspace
description: "Widgetbook workspace for building widgets and screens in isolation"
version: 0.1.0
publish_to: "none"

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  ui:
    path: ../
  widgetbook_annotation: ^3.9.0
  widgetbook: ^3.20.0
  intl: ^0.20.2
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  widgetbook_generator: ^3.20.0

flutter:
  uses-material-design: true

  fonts:
    - family: ibmPlexSansThai
      fonts:
        - asset: ../assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Thin.ttf
        - asset: ../assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-ExtraLight.ttf
        - asset: ../assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Light.ttf
        - asset: ../assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Regular.ttf
        - asset: ../assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Medium.ttf
        - asset: ../assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-SemiBold.ttf
        - asset: ../assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Bold.ttf
