name: auth
description: "Authentication module for Money Tracker application."
version: 0.0.1
publish_to: "none"
resolution: "workspace"

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared:
    path: ../shared
  ui:
    path: ../ui
  settings:
    path: ../settings
  flutter_facebook_auth: ^7.1.2
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.2
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
  assets:
    - ./assets/translations/
