name: auth
description: "Authentication module for Money Tracker application."
version: 0.0.1
publish_to: "none"
resolution: "workspace"

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  easy_localization: ^3.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_facebook_auth: ^7.1.2
  flutter_form_builder: ^10.2.0
  flutter_hooks: ^0.21.3+1
  flutter_screenutil: ^5.9.3
  form_builder_validators: ^11.2.0
  fpdart: ^1.2.0
  freezed_annotation: ^3.1.0
  go_router: ^17.0.0
  google_sign_in: ^7.2.0
  json_annotation: ^4.9.0
  shared:
    path: ../shared
  ui:
    path: ../ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.2
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  flutter_gen: ^5.12.0
  flutter_gen_runner: ^5.12.0

flutter:
  assets:
    - ./assets/translations/

flutter_gen:
  output: ./lib/generated
  line_length: 120
  assets:
    enabled: true
    outputs:
      style: dot-delimiter
      class_name: UiAssets
      package_parameter_enabled: true
    exclude:
      - assets/translations/**
