name: settings
description: "Settings module for Money Tracker application."
version: 0.0.1
publish_to: "none"
resolution: "workspace"

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared:
    path: ../shared
  ui:
    path: ../ui
  country_flags: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen: ^5.12.0
  flutter_gen_runner: ^5.12.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
  assets:
    - ./assets/translations/

flutter_gen:
  output: ./lib/generated
  line_length: 120
  assets:
    enabled: true
    outputs:
      style: dot-delimiter
      class_name: UiAssets
      package_parameter_enabled: true
    exclude:
      - assets/translations/**
