name: settings
description: "Settings module for Money Tracker application."
version: 0.0.1
publish_to: "none"
resolution: "workspace"

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  easy_localization: ^3.0.8
  flutter:
    sdk: flutter
  shared:
    path: ../shared
  ui:
    path: ../ui
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  go_router: ^17.0.0
  flutter_hooks: ^0.21.3+1
  country_flags: ^4.1.0
  font_awesome_flutter: ^10.12.0
  fpdart: ^1.2.0
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen: ^5.12.0
  flutter_gen_runner: ^5.12.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
  assets:
    - ./assets/translations/

flutter_gen:
  output: ./lib/generated
  line_length: 120
  assets:
    enabled: true
    outputs:
      style: dot-delimiter
      class_name: UiAssets
      package_parameter_enabled: true
    exclude:
      - assets/translations/**
