name: ui
description: "UI module for Money Tracker application."
version: 0.0.1
publish_to: "none"
resolution: "workspace"

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  easy_localization: ^3.0.8
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.2.0
  flutter_hooks: ^0.21.3+1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.2
  font_awesome_flutter: ^10.12.0
  form_builder_validators: ^11.2.0
  go_router: ^17.0.0
  shared:
    path: ../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen: ^5.12.0
  flutter_gen_runner: ^5.12.0

flutter:
  assets:
    - ./assets/images/
    - ./assets/translations/

  fonts:
    - family: ibmPlexSansThai
      fonts:
        - asset: ./assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Thin.ttf
        - asset: ./assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-ExtraLight.ttf
        - asset: ./assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Light.ttf
        - asset: ./assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Regular.ttf
        - asset: ./assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Medium.ttf
        - asset: ./assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-SemiBold.ttf
        - asset: ./assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Bold.ttf

flutter_gen:
  output: ./lib/generated
  line_length: 120
  assets:
    enabled: true
    outputs:
      style: dot-delimiter
      class_name: UiAssets
      package_parameter_enabled: true
    exclude:
      - assets/translations/**
